import 'dart:io';

timetableTest(location) {
  print('*************** Current ***************');
  print('dawn:\t\t${location.prayers.current.dawn}');
  print('sunrise:\t${location.prayers.current.sunrise}');
  print('midday:\t\t${location.prayers.current.midday}');
  print('afternoon:\t${location.prayers.current.afternoon}');
  print('sunset:\t\t${location.prayers.current.sunset}');
  print('dusk:\t\t${location.prayers.current.dusk}');
  print('**************** Next *****************');
  print('dawn:\t\t${location.prayers.next.dawn}');
  print('sunrise:\t${location.prayers.next.sunrise}');
  print('midday:\t\t${location.prayers.next.midday}');
  print('afternoon:\t${location.prayers.next.afternoon}');
  print('sunset:\t\t${location.prayers.next.sunset}');
  print('dusk:\t\t${location.prayers.next.dusk}');
  print('************** Previous ***************');
  print('dawn:\t\t${location.prayers.previous.dawn}');
  print('sunrise:\t${location.prayers.previous.sunrise}');
  print('midday:\t\t${location.prayers.previous.midday}');
  print('afternoon:\t${location.prayers.previous.afternoon}');
  print('sunset:\t\t${location.prayers.previous.sunset}');
  print('dusk:\t\t${location.prayers.previous.dusk}');
  print('*************** Sunnah *****************');
  print('midnight:\t${location.sunnah.midnight}');
  print('lastThird\t${location.sunnah.lastThird}');
  print('************** Calc ***************');
  print('time:\t${location.calc.time}');
  print('current:\t${location.calc.current}');
  print('next:\t\t${location.calc.next}');
  print('previous:\t${location.calc.previous}');
  print('isAfterIsha:\t${location.calc.isAfterIsha}');
  print('currentId:\t${location.calc.currentId}');
  print('countDown:\t${location.calc.countDown}');
  print('countUp:\t${location.calc.countUp}');
  print('countDown calcToday:\t${location.calcToday.countDown}');
  print('countUp calcToday:\t${location.calcToday.countUp}');
  print('Qibla:\t${location.calc.qibla}');
  print('percentage:\t${location.calc.percentage}');
}

jamaahTest(location) {
  print('**************** Today *****************');
  print('dawn:\t\t${location.prayers.current.dawn}');
  print('sunrise:\t${location.prayers.current.sunrise}');
  print('midday:\t\t${location.prayers.current.midday}');
  print('afternoon:\t${location.prayers.current.afternoon}');
  print('sunset:\t\t${location.prayers.current.sunset}');
  print('dusk:\t\t${location.prayers.current.dusk}');
  print('*************** Tomorrow **************');
  print('dawn:\t\t${location.prayers.next.dawn}');
  print('sunrise:\t${location.prayers.next.sunrise}');
  print('midday:\t\t${location.prayers.next.midday}');
  print('afternoon:\t${location.prayers.next.afternoon}');
  print('sunset:\t\t${location.prayers.next.sunset}');
  print('dusk:\t\t${location.prayers.next.dusk}');
  print('************** Yesterday ***************');
  print('dawn:\t\t${location.prayers.previous.dawn}');
  print('sunrise:\t${location.prayers.previous.sunrise}');
  print('midday:\t\t${location.prayers.previous.midday}');
  print('afternoon:\t${location.prayers.previous.afternoon}');
  print('sunset:\t\t${location.prayers.previous.sunset}');
  print('dusk:\t\t${location.prayers.previous.dusk}');
  print('************ Today Jamaah *************');
  print('dawn:\t\t${location.jamaah.current.dawn}');
  print('sunrise:\t${location.jamaah.current.sunrise}');
  print('midday:\t\t${location.jamaah.current.midday}');
  print('afternoon:\t${location.jamaah.current.afternoon}');
  print('sunset:\t\t${location.jamaah.current.sunset}');
  print('dusk:\t\t${location.jamaah.current.dusk}');
  print('*********** Tomorrow Jamaah ***********');
  print('dawn:\t\t${location.jamaah.next.dawn}');
  print('sunrise:\t${location.jamaah.next.sunrise}');
  print('midday:\t\t${location.jamaah.next.midday}');
  print('afternoon:\t${location.jamaah.next.afternoon}');
  print('sunset:\t\t${location.jamaah.next.sunset}');
  print('dusk:\t\t${location.jamaah.next.dusk}');
  print('********** Yesterday Jamaah ***********');
  print('dawn:\t\t${location.jamaah.previous.dawn}');
  print('sunrise:\t${location.jamaah.previous.sunrise}');
  print('midday:\t\t${location.jamaah.previous.midday}');
  print('afternoon:\t${location.jamaah.previous.afternoon}');
  print('sunset:\t\t${location.jamaah.previous.sunset}');
  print('dusk:\t\t${location.jamaah.previous.dusk}');
  print('*************** Sunnah *****************');
  print('midnight:\t${location.sunnah.midnight}');
  print('lastThird\t${location.sunnah.lastThird}');
  print('************** Calc ***************');
  print('time:\t${location.calc.time}');
  print('current:\t${location.calc.current}');
  print('next:\t\t${location.calc.next}');
  print('previous:\t${location.calc.previous}');
  print('isAfterIsha:\t${location.calc.isAfterIsha}');
  print('jamaahPending:\t${location.calc.jamaahPending}');
  print('currentId:\t${location.calc.currentId}');
  print('countDown:\t${location.calc.countDown}');
  print('countUp:\t${location.calc.countUp}');
  print('percentage:\t${location.calc.percentage}');
  // print(location.current);
}
