include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  exclude: [build/**, lib/*.dart_]
  # strong-mode:
  #   implicit-casts: false
  #   implicit-dynamic: false

linter:
  rules:
    # - annotate_overrides
    # - await_only_futures
    camel_case_types: true
    # - cancel_subscriptions
    # - close_sinks
    # - comment_references
    # - constant_identifier_names
    # - control_flow_in_finally
    # - empty_statements
    curly_braces_in_flow_control_structures: false
