# include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
    exclude: [build/**, lib/*.dart_]
    # strong-mode:
    #   implicit-casts: false
    #   implicit-dynamic: false

linter:
    rules:
        annotate_overrides: true
        # - await_only_futures
        # - cancel_subscriptions
        # - close_sinks
        # - comment_references
        # - constant_identifier_names
        # - control_flow_in_finally
        # - empty_statements
        curly_braces_in_flow_control_structures: false
        camel_case_types: true
        # avoid_print: false  # Uncomment to disable the `avoid_print` rule
        # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
        prefer_single_quotes: true
        file_names: false
        prefer_initializing_formals: false
