include: package:flutter_lints/flutter.yaml

analyzer:
    exclude:
        - build/**
        - lib/*.dart_
        - lib/src/func/old/**
        - example/**

linter:
    rules:
        # Additional rules for better code quality
        prefer_single_quotes: true
        file_names: false
        prefer_initializing_formals: false
        curly_braces_in_flow_control_structures: false

        # Documentation rules
        public_member_api_docs: false # We have comprehensive inline docs

        # Allow prints in examples and tests
        avoid_print: false
