name: prayer_timetable
version: 1.0.8
description: >-
  Library to calculate prayer times for muslims.
  Based on precise astronomical formula.
homepage: https://ensar.me
documentation: https://ensar.me/docs
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  adhan_dart: ^1.0.7

dev_dependencies:
  timezone: ^0.8.0
