name: prayer_timetable
version: 2.2.3
description: >-
    Comprehensive Dart library for Islamic prayer time calculations with multiple methods,
    jamaah time management, timezone support, and Hijri calendar integration.
homepage: https://github.com/prayer-timetable/prayer_timetable_dart
repository: https://github.com/prayer-timetable/prayer_timetable_dart
issue_tracker: https://github.com/prayer-timetable/prayer_timetable_dart/issues
documentation: https://github.com/prayer-timetable/prayer_timetable_dart#readme
environment:
    sdk: '>=3.3.0 <4.0.0'
dependencies:
    adhan_dart: ^1.2.0
    hijri: ^3.0.0
    timezone: ^0.10.1

dev_dependencies:
    flutter_lints: ^6.0.0
    date_format: ^2.0.9

topics:
    - islam
    - prayer
    - muslim
    - adhan
    - hijri
